### PR TITLE
B11 API Input Laptop (Create)

### PR DESCRIPTION
**Pull request by Fazamazaya**
DATABASE : '2023_5pagia_laptop'
Screenshot 2023-12-26 160635
Screenshot 2023-12-26 160537

TAMPILAN TABLE 'LAPTOP' SEBELUM 
Screenshot 2023-12-26 102610

POSTMAN MENGGUNAKAN THUNDER CLIENT DI VS CODE
SS POSTMAN

TAMPILAN TABLE 'LAPTOP' SESUDAH
Screenshot 2023-12-26 102713

FILE upload/gambar.jpg
Screenshot 2023-12-26 160857

@aldhi88 @aldhisttd

### CODE REVIEW

**Review by aldhi88 — CHANGES_REQUESTED** [review]
@Fazamazaya , mana screen shot postman dan databasenya, jgn lupa ss file uploadnya juga lampirkan

**Review by aldhi88 — CHANGES_REQUESTED** [review]
@Fazamazaya , coba pull master dulu, baru push ulang

**Comment by Fazamazaya** [comment]
@aldhi88 @aldhisttd sudah push ulang pak

**Comment by Fazamazaya** [comment]
> @Fazamazaya , coba pull master dulu, baru push ulang

@aldhi88 @aldhisttd sudah push ulang pak

**Review by aldhi88 — CHANGES_REQUESTED** [review]
@Fazamazaya , pull master sebelum push

**Pull request closed without merging**
